# # Used to get an access token given an autorization key
#   @baseUrl = https://apigw.nubentos.com:443
# @authorization = OXhzZmZfZmVuVnlzR0g5aVhiMzR5d1BYRHgwYTprTU1sdERzeGR5aUFiTExHUV85U3FDOUNNZnNh
POST {{baseUrl}}/token?grant_type=client_credentials
Authorization: Basic {{authorization}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/cases?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/todayCases?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/active?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/deaths?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/todayDeaths?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/recovered?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/critical?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/casesPerOneMillion?country=Egypt
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/deathsPerOneMillion
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/totalTests
Accept: "application/json"
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/2.0.0/testsPerOneMillion
Accept: "application/json"
Authorization: Bearer {{accessToken}}